on:
  push:
    branches:
      - gh-pages

name: build gatsby

jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.HWINKR_BLOG}}
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HWINKR_BLOG_TOKEN }}
          publish_dir: ./public
